### ISSUE TITLE
Own Repo

### ISSUE THREAD

**Issue by velotoxicsounds** [LambentLight/Metadata#13]
Hello

is it possible to host your own repo? Unfortunately, I miss the Convert.bat. I built my repo like that, but it doesn't load the newly added things in LambentLight Manager. A small manual is subject to toll :) As soon as I build able resources I would send them to you too (FORGE)

**Comment by justalemon** [comment]
Hi, sorry for not documenting it but the format of the Resource Repositories changed with the release of LambentLight 2.0

You can install Python 3.5 or higher and run the `tools` module to make the management easier:

* `python -m tools` or `python -m tools all` to update resources, builds and versions at the same time
* `python -m tools new` for adding new resources with a step-by-step process
* `python -m tools builds` to update the list of builds from the CFX Download page
* `python -m tools versions` to update the versions of each resource
* `python -m tools versionsmanual` to update the version of a single resource
* `python -m tools list` to update the list of resources for each game (`gtav.json`, `rdr2.json` and `common.json`)

Once I finish with a couple of features on the LambentLight app, I'm going to document everything.

**Comment by velotoxicsounds** [comment]
Wow thank you for the quick response. I will test your instructions immediately afterwards. I will then run you the next few days to send you my repo so that your database grows steadily. Thank you very much for your efforts, I will send you a small donation 👍 great software

**Comment by justalemon** [comment]
Instead of creating a new repo and sending it, you can just Fork it, make the changes and send them via a pull request. By doing this, you will be credited for the changes as long as the repo exists on GitHub!

**Comment by velotoxicsounds** [comment]
python -m tools or python -m tools all i doenst can use, CODE: 
A GitHub Token is required for updating all of the versions at the same time..

The rest worked, I was able to integrate the first resource successfully. I made a pull request for this. I'm going to start building a lot of things in over the next few days.

Is it possible to enter a path folder at the destination folder?

Example:
Destanation Folder: [LSFD]/esx_FireDispatch

I tested it, but unfortunately it didn't work. I have therefore registered only esx_FireDispatch now. I think it's only easier if you can keep track as a server owner when we use a fixed folder structure. Just as a suggestion. Doesn't necessarily have to be

**Comment by justalemon** [comment]
As the message says, you need to enter a GitHub token via environment variables.

Go to https://github.com/settings/tokens. generate a token and add it onto the CMD Window via the set command, like this:

```
Microsoft Windows [Version 10.0.18363.535]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\lemon>set GITHUB_TOKEN=PASTE_YOUR_TOKEN_HERE

C:\Users\lemon>python -m tools all
```
